# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(email: "luneya@gmail.com", username: "luneya", first_name: "luneya", last_name: "luneya", password: "123456")
User.create(email: "aquaman@gmail.com", username: "aquaman",first_name: "aquaman", last_name: "aquaman", password: "abcdef")
User.create(email: "spongebob@gmail.com", username: "spongebob",first_name: "spongebob", last_name: "squarepants", password: "abcdef") 
User.create(email: "ariel@gmail.com", username: "ariel",first_name: "ariel", last_name: "ariel", password: "abcdef")
User.create(email: "patrick@gmail.com", username: "patrick",first_name: "patrick", last_name: "star", password: "abcdef")
User.create(email: "nemo@gmail.com", username: "nemo",first_name: "nemo", last_name: "nemo", password: "abcdef")
User.create(email: "dory@gmail.com", username: "dory",first_name: "dory", last_name: "dory", password: "abcdef")

Fish.create(name: "Catfish", image_path: "catfish.png")
Fish.create(name: "Clownfish", image_path: "clownfish.png")
Fish.create(name: "Fish 1", image_path: "fish1.png")
Fish.create(name: "Fish 2", image_path: "fish2.png")
Fish.create(name: "Fish 3", image_path: "fish3.png")
Fish.create(name: "Fish 4", image_path: "fish4.png")
Fish.create(name: "Fish 5", image_path: "fish5.png")
Fish.create(name: "Fred", image_path: "fred.png")
Fish.create(name: "Goldfish", image_path: "goldfish.png")
Fish.create(name: "Goldfish 2", image_path: "goldfish2.png")
Fish.create(name: "Jellyfish1", image_path: "jellyfish1.png")
Fish.create(name: "Jellyfish2", image_path: "jellyfish2.png")
Fish.create(name: "Jellyfish3", image_path: "jellyfish3.png")
Fish.create(name: "Jellyfish4", image_path: "jellyfish4.png")
Fish.create(name: "Jellyfish5", image_path: "jellyfish5.png")
Fish.create(name: "Whale 1", image_path: "whale1.png")
Fish.create(name: "Whale 2", image_path: "whale2.png")
Fish.create(name: "Shrimp 1", image_path: "shrimp1.png")
Fish.create(name: "Shrimp 2", image_path: "shrimp2.png")

User.find(1).fishes << Fish.find(1)
User.find(1).fishes << Fish.find(2)
User.find(1).fishes << Fish.find(3)
User.find(2).send_request_to(User.find(1))
User.find(3).send_request_to(User.find(1))
User.find(4).send_request_to(User.find(1))
User.find(5).send_request_to(User.find(1))
User.find(6).send_request_to(User.find(1))
User.find(7).send_request_to(User.find(1))

