# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(email: "luneya@gmail.com", username: "luneya", first_name: "luneya", password: "123456")
User.create(email: "bob@gmail.com", username: "bob",first_name: "bob", password: "abcdef")
User.create(email: "jim@gmail.com", username: "jim",first_name: "jim", password: "abcdef") 
User.create(email: "fred@gmail.com", username: "fred",first_name: "fred", password: "abcdef")
User.create(email: "honk@gmail.com", username: "honk",first_name: "honk", password: "abcdef")
User.create(email: "fia@gmail.com", username: "fia",first_name: "fia", password: "abcdef")
User.create(email: "jabari@gmail.com", username: "jabari",first_name: "jabari", password: "abcdef")
User.create(email: "hardone@gmail.com", username: "hardone", first_name: "hardone", password: "abcdef")
User.create(email: "moonshine@gmail.com", username: "moonshine", first_name: "moonshine", password: "abcdef")
User.create(email: "bev@gmail.com", username: "bev", first_name: "bev", password: "abcdef")
User.create(email: "balnor@gmail.com", username: "balnor", first_name: "balnor", password: "abcdef")
User.create(email: "onyx@gmail.com", username: "onyx", first_name: "onyx", password: "abcdef")
User.create(email: "pawpaw@gmail.com", username: "pawpaw", first_name: "pawpaw", password: "abcdef")

User.create(email: "mars@gmail.com", username: "mars", first_name: "mars", password: "abcdef")
User.create(email: "kevin@gmail.com", username: "kevin", first_name: "kevin", password: "abcdef")
User.create(email: "alan@gmail.com", username: "alan", first_name: "alan", password: "abcdef")
User.create(email: "shay@gmail.com", username: "shay", first_name: "shay", password: "abcdef")
User.create(email: "scanlin@gmail.com", username: "scanlin", first_name: "scanlin", password: "abcdef")
User.create(email: "mavrus@gmail.com", username: "mavrus", first_name: "mavrus", password: "abcdef")
User.create(email: "deadeye@gmail.com", username: "deadeye", first_name: "deadeye", password: "abcdef")
User.create(email: "galad@gmail.com", username: "galad", first_name: "galad", password: "abcdef") 

Fish.create(name: "Catfish", image_path: "catfish.png", desc: "The fish goes meow.")
Fish.create(name: "Clownfish", image_path: "clownfish.png")
Fish.create(name: "Fish 1", image_path: "fish1.png")
Fish.create(name: "Goldfish", image_path: "goldfish.png")
Fish.create(name: "Goldfish 2", image_path: "goldfish2.png")
Fish.create(name: "Jellyfish1", image_path: "jellyfish1.png")
Fish.create(name: "Jellyfish2", image_path: "jellyfish2.png")
Fish.create(name: "Jellyfish3", image_path: "jellyfish3.png")
Fish.create(name: "Jellyfish4", image_path: "jellyfish4.png")
Fish.create(name: "Jellyfish5", image_path: "jellyfish5.png")
Fish.create(name: "Whale 1", image_path: "whale1.png")
Fish.create(name: "Whale 2", image_path: "whale2.png")
Fish.create(name: "Shrimp 1", image_path: "shrimp1.png")
Fish.create(name: "Shrimp 2", image_path: "shrimp2.png")

User.find(1).fishes << Fish.find(1)
User.find(1).fishes << Fish.find(2)
User.find(1).fishes << Fish.find(3)